[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["node_modules/@netlify/plugin-nextjs/**/*"]
